# Generated by Django 3.2.15 on 2024-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='заказы', to='foodcartapp.Product'),
        ),
    ]
