# Generated by Django 3.2.15 on 2024-05-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20240511_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='элементы_заказа', to='foodcartapp.product', verbose_name='элемент'),
        ),
    ]
