# Generated by Django 3.2.15 on 2024-05-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20240511_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='surname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
