# Generated by Django 3.2.15 on 2024-05-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20240512_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderelement',
            old_name='element',
            new_name='product',
        ),
    ]
