# Generated by Django 3.2.15 on 2024-05-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20240514_1304'),
        ('foodcartapp', '0046_auto_20240514_1313'),
    ]

    operations = [
    ]
