# Generated by Django 3.2.15 on 2024-05-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20240514_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Начат'), ('accepted', 'Принят'), ('in_progress', 'Собирается'), ('being_delivered', 'В доставке'), ('delivered', 'Выполнен')], default='received', max_length=20),
        ),
    ]
