# Generated by Django 3.2.15 on 2024-05-15 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='уточнен в'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='доставлен в'),
        ),
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='поступил в'),
        ),
    ]
