# Generated by Django 3.2.15 on 2024-05-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20240515_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Электронно')], db_index=True, default='cash', max_length=20),
        ),
    ]
