# Generated by Django 3.2.15 on 2024-05-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_chosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.restaurant', verbose_name='Где готовить'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurants_choice',
            field=models.TextField(blank=True, max_length=200, verbose_name='Варианты ресторанов'),
        ),
    ]
