# Generated by Django 3.2.15 on 2024-05-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20240516_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant_chosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.restaurant', verbose_name='Где готовить'),
        ),
    ]
