# Generated by Django 3.2.15 on 2024-05-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_restaurant_chosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='адрес текстом')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=14, verbose_name='долгота')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=14, verbose_name='широта')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='обновлялись в')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='foodcartapp.restaurant', verbose_name='ресторан')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
            },
        ),
    ]
